version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nest_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh 
    volumes:
      - ./backend:/app:cached
      - /app/node_modules
    command: npm run start:dev

  event-portal:
    build: 
      context: ./frontend/next-event-portal
      args:
        NEXT_PUBLIC_API_URL: http://10.0.10.29:3000/api/v1
    container_name: next_event_portal
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - AUTH_SECRET=super-secret-nextauth-key-change-in-production
      - AUTH_URL=http://10.0.10.29:3001
      - API_INTERNAL_URL=http://nest_backend:3000/api/v1
    extra_hosts:
      - "10.0.10.29:host-gateway"

  super-admin:
    build: 
      context: ./frontend/super-admin-nextjs
      args:
        NEXT_PUBLIC_API_URL: http://10.0.10.29:3000/api/v1
    container_name: super_admin_nextjs
    ports:
      - "3002:3000"
    depends_on:
      - backend
    extra_hosts:
      - "10.0.10.29:host-gateway"

volumes:
  postgres_data:
    external: true
    name: backend_postgres_data